version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: all   # includes direct and indirect dependencies

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
