require:
  - rubocop-rspec

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

RSpec/NestedGroups:
  Max: 4

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/integration/rackup_spec.rb'
    - 'spec/journey/*'
