require:
  - rubocop-rspec

inherit_gem:
  rubocop-govuk:
    - config/default.yml

Metrics/BlockLength:
  IgnoredMethods: ['get']
RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']
RSpec/NestedGroups:
  Max: 4
