version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
      nodejs: 18
    commands:
      - bundle install
      - npm install
      - make hosts
  build:
    commands:
      - make frontend-build
      - make test
