version: 0.2

runtime-versions:
  ruby: 2.6
  nodejs: 10

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-integration"

  parameter-store:
    PAAS_LOGIN_INTEGRATION: "epbr-govpaas-integration-login"
    PAAS_PW_INTEGRATION: "epbr-govpaas-integration-pw"
    PAAS_SPACE_INTEGRATION: "epbr-govpaas-integration-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"

phases:
  install:
    runtime-versions:
      ruby: 2.6
      nodejs: 10
    commands:
      - bundle install
      - npm install
      - make hosts
  build:
    commands:
      - make frontend-build
      - make test
