version: 0.2

env:
  variables:
    DEPLOY_APPNAME: "epbr-frontend-integration"

phases:
  install:
    runtime-versions:
      ruby: 3.x

  pre_build:
    commands:
      - sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
      - sudo apt-get update
      - sudo apt-get install pack-cli
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -;
      - sudo apt-get update -qq
      - sudo apt-get install -qq --no-install-recommends nodejs
      - sudo apt-get clean
      - sudo rm -rf /var/lib/apt/lists/*
      - mv AWS-Procfile Procfile
      - npm install
      - bundle install
      - ruby ./build/compile_assets.rb

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Paketo image...
      - pack build ebpr-frontend-image --buildpack paketo-buildpacks/ruby --builder paketobuildpacks/builder:base

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o ebpr-frontend-image.tar ebpr-frontend-image:latest

artifacts:
  files:
    - '**/*'
