version: 0.2

runtime-versions:
  ruby: 2.7
  nodejs: 14

phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 14
    commands:
      - bundle install
      - npm install
      - make hosts
  build:
    commands:
      - make frontend-build
      - make test
