version: 0.2

runtime-versions:
  ruby: 2.7
  nodejs: 14

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-staging"
    STATIC_START_PAGE_FINDING_EN: "https://mhclg-epb-static-start-pages-staging.london.cloudapps.digital/find-an-energy-certificate.html"
    STATIC_START_PAGE_GETTING_EN: "https://mhclg-epb-static-start-pages-staging.london.cloudapps.digital/getting-a-new-energy-certificate.html"
    STATIC_START_PAGE_FINDING_CY: "https://mhclg-epb-static-start-pages-staging.london.cloudapps.digital/chwiliwch-am-dystysgrif-ynni.html"
    STATIC_START_PAGE_GETTING_CY: "https://mhclg-epb-static-start-pages-staging.london.cloudapps.digital/sicrhau-tystysgrif-ynni-newydd.html"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-staging-login"
    PAAS_PW: "epbr-govpaas-staging-pw"
    PAAS_SPACE: "epbr-govpaas-staging-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_AUTH_CLIENT_ID: "epbr-frontend-auth-client-id-staging"
    EPB_AUTH_CLIENT_SECRET: "epbr-frontend-auth-client-secret-staging"
    EPB_AUTH_SERVER: "epbr-auth-server-staging"
    EPB_API_URL: "epbr-api-url-staging"
    EPB_UNLEASH_URI: "epbr-unleash-staging-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-staging-auth-token"
    SENTRY_DSN: "epbr-sentry-dsn-frontend"

phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 14
    commands:
      - npm install
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO STAGING ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
  post_build:
    commands:
      - cf logout
