version: 0.2

runtime-versions:
  ruby: 2.7
  nodejs: 14

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-frontend-ui-production"
    GTM_PROPERTY_FINDING: "GTM-5CVJ2P9"
    GTM_PROPERTY_GETTING: "GTM-NHXWZF5"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-production-login"
    PAAS_PW: "epbr-govpaas-production-pw"
    PAAS_SPACE: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_AUTH_CLIENT_ID: "epbr-frontend-auth-client-id-production"
    EPB_AUTH_CLIENT_SECRET: "epbr-frontend-auth-client-secret-production"
    EPB_AUTH_SERVER: "epbr-auth-server-production"
    EPB_API_URL: "epbr-api-url-production"
    EPB_UNLEASH_URI: "epbr-unleash-production-uri"
    EPB_RECAPTCHA_SITE_KEY: "epbr-recaptcha-site-key"
    EPB_RECAPTCHA_SITE_SECRET: "epbr-recaptcha-secret-key"
    EPB_SUSPECTED_BOT_USER_AGENTS: "epbr-suspected-bot-user-agents"
    SENTRY_DSN: "epbr-sentry-dsn-frontend"

phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 14
    commands:
      - npm install
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO PRODUCTION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
  post_build:
    commands:
      - cf logout
